version: "3"
services:
  install:
    image: node:22.0.0
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && yarn && cd /app/docs && rm -rf node_modules && yarn"
  build:
    image: node:22.0.0
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && yarn build"
  bundle:
    image: node:22.0.0
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app && yarn bundle"
  lint:
    image: node:22.0.0
    user: node
    volumes:
      - .:/app
    command: bash -c "cd /app && yarn fmt && yarn lint:all"
  dev:
    #docker-compose run --rm dev bash
    # user: node
    image: node:22.0.0
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true
